//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMakeTools {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CMakeStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CMakeStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CMakeTools.CMakeStrings", typeof(CMakeStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All subdirectories.
        /// </summary>
        internal static string AllSubdirectories {
            get {
                return ResourceManager.GetString("AllSubdirectories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only subdirectories containing CMakeLists.txt.
        /// </summary>
        internal static string CMakeListsOnly {
            get {
                return ResourceManager.GetString("CMakeListsOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CMake could not be found on your computer.  Please ensure that it is properly installed..
        /// </summary>
        internal static string CMakeNotFound {
            get {
                return ResourceManager.GetString("CMakeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CMake Snippet.
        /// </summary>
        internal static string CMakeSnippet {
            get {
                return ResourceManager.GetString("CMakeSnippet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command is deprecated..
        /// </summary>
        internal static string DeprecatedCommand {
            get {
                return ResourceManager.GetString("DeprecatedCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected: command or function call..
        /// </summary>
        internal static string ExpectedCommand {
            get {
                return ResourceManager.GetString("ExpectedCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected: end of line..
        /// </summary>
        internal static string ExpectedEOL {
            get {
                return ResourceManager.GetString("ExpectedEOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected: &apos;(&apos;..
        /// </summary>
        internal static string ExpectedOpenParen {
            get {
                return ResourceManager.GetString("ExpectedOpenParen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while launching CMake..
        /// </summary>
        internal static string FailedToLaunchCMake {
            get {
                return ResourceManager.GetString("FailedToLaunchCMake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &apos;{0}&apos; could not be found..
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid escape sequence..
        /// </summary>
        internal static string InvalidEscapeSequence {
            get {
                return ResourceManager.GetString("InvalidEscapeSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid variable reference..
        /// </summary>
        internal static string InvalidVariableRef {
            get {
                return ResourceManager.GetString("InvalidVariableRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CMake Tools for Visual Studio.
        /// </summary>
        internal static string MessageBoxTitle {
            get {
                return ResourceManager.GetString("MessageBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unmatched parenthesis..
        /// </summary>
        internal static string UnmatchedParen {
            get {
                return ResourceManager.GetString("UnmatchedParen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
